export interface ITestEntityData {
    entityWords: string[];
    containingQueries: string[];
}

export type TestEntitiesDataSet = ITestEntityData[];

const entitiesDataSet1: TestEntitiesDataSet = [
    {
        containingQueries: [
            "react function component",
            "react inline component",
            "react button disabled",
            "enzyme find by react key",
            "react testing library shallow",
            "react test id",
            "react testid",
            "should i test for react state",
            "react tutorial",
            "create react app",
            "react force removal on props change",
            "create react app",
            "react 16.7",
            "storybook/app/react/bin/build.js",
            "react rendering a promise",
            "react rendering a promis",
            "react shouldComponentUpdate",
            "react changes in props not causing componentDidUpdate",
            "promise.then in a react component",
            "react promises as props",
            "react computed state",
            "react setting a global function",
            "react detect node env",
            "react-dom.development.js:506 Warning: Expected instance state to match memoized state before processing the update queue. This is likely due to a bug in React. Please file an issue.",
            "react component didupdaer",
            "react broadcast event",
            "vscode react extensions",
            "react classname vscode show",
            "vscode go to react class css",
            "babel preset react app",
            "missing class properties transform. react babelrc",
            "missing class properties transform. react",
            "babel react babelrc",
            "\"@babel/react\"",
            "babel loader Couldn't find preset \"@babel/react\" relative to directory",
            "Couldn't find preset \"@babel/react\"",
            "npm create react app",
            "react dom intersectionobserver \"test\"",
            "react dom intersectionobserver tests",
            "esModuleInterop react classnames",
            "react classnames example",
            "react enzyme test child props",
            "jest test with react.createref",
            "enzyme get react ref",
            "react test with context",
            "react setstate requestanimationframe",
            "react setState which thread",
            "where do react setState runs main thread",
            "where do react setState runs",
            "react shouldcomponentupdate",
            "react this state undefined",
            "react context render on change",
            "react context force rerender",
            "react context function re-render",
            "react context function re-renderer",
            "react spread props",
            "react consumer context using componentdidmount",
            "react typescript ref type",
            "react context example tsx",
            "react noop",
            "react storybook click",
            "react classnames npm",
            "async test react jest",
            "react \"functioncomponent\"",
            "react functioncomponent",
            "react functionalcomponent",
            "react enzyme testshallow render",
            "react render props type typescript",
            "react render props",
            "react components with typescript generic",
            "react loadable example",
            "react multiple elements without wrapper",
            "react multiple elements without wrapper",
            "react euivalent to ng if",
            "react lifecycle",
            "react js roadmap",
            "react emotion",
            "create react app change port 3000",
            "create react app start on different port",
            "create react app typescript",
            "play react seed",
            "besst editors for frontend react",
        ],
        entityWords: [
            "react",
        ],
    },
    {
        containingQueries: [
            "jest does not recompile",
            "TypeError: ShallowWrapper::dive() can not be called on Host Components",
            "jest mount component not working well",
            "not good enough funny",
            "not good enough meme",
            "chef gordon not good enough meme",
            "chef gordon not good enough meme",
            "chef gordon not good enough meme",
            "chef gordon not good enough",
            "chef gordon not good enough",
            "not good enough meme",
            "not good enough meme",
            "not good enough meme",
            "intellij do not suggest css optimization",
            "css do not break line",
            "storybook do not build on error",
            "react changes in props not causing componentDidUpdate",
            "reactr not detecting changes in props",
            "jest enzyme context provder context is not used",
            "jest enzyme test context not being updated",
            "npm jsdom \"Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)\"",
            "npm jsdom Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)",
            "Error: Not implemented: HTMLCanvasElement.prototype.getContext jsdom",
            "super expression must either be null or a function, not object es6",
            "n\"!=typeof t&&null!==t)throw new TypeError(\"Super expression must either be null or a function, not \"+typeof t);",
            "Running as root without --no-sandbox is not supported \"applitools\"",
            "Running as root without --no-sandbox is not supported applitools",
            "Running as root without --no-sandbox is not supported",
            "Chromium revision is not downloaded. Run \"npm install\" or \"yarn install\" docker",
            "Chromium revision is not downloaded. Run \"npm install\" or \"yarn install\"",
            "ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported",
            "jest \"intersectionobserver\" is not defined",
            "jest IntersectionObserver is not defined",
            "jest ReferenceError: IntersectionObserver is not defined",
            "jest mock not working module",
            "Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)",
            "es6 sort not in place",
            "File node_modules/@types/classNames/index.d.ts is not a module. \"classNames\"",
            "File node_modules/@types/classNames/index.d.ts is not a module.",
            "enzyme not exist",
            "componentDidMount jest shallow not called",
            "url-loader not found webpack font",
            "url-loader not found webpack",
            "Module not found: Error: Can't resolve './fonts/ProximaNova-Light.woff'",
            "start-storybook (stderr): Could not open",
            "@applitools/eyes.storybook eyes-storybook Could not open http://localhost:6006/ inside a browser",
            "storybook ERR! Could not open http://localhost:6006/ inside a browser. If you're running this command inside a",
            "ERR! Could not open http://localhost:6006/ inside a browser. If you're running this command inside a",
            "tslint does not fail",
            "com.typesafe.config.ConfigException$IO dev.application.conf: java.io.IOException: resource not found on classpath",
            "resource not found on classpath: dev.application.conf",
            "play config not found in path",
            "SecurityError: localStorage is not available for opaque origins test",
        ],
        entityWords: [
            "not",
        ],
    },
    {
        containingQueries: [
            "jest visual studio code window",
            "visual studio code run tests jest",
            "npm jest esm",
            "jest \"SyntaxError: Unexpected token export\" es modules",
            "jest SyntaxError: Unexpected token export",
            "jest enzyme check for attribute",
            "jest perform type check typescript",
            "jest perform type check",
            "jest does not recompile",
            "jest compare only existing properties",
            "jest transform js files",
            "testing HOC with promises jest",
            "jest mount component not working well",
            "jest testing elements with promises",
            "jest expect async",
            "jest expect async to throw",
            "jest mockResolvedValue",
            "jest auto restoreAllMocks",
            "jest reset spyon",
            "jest reset call count",
            "jest reset changed modules between tests",
            "jest reset imports",
            "jest expect one of",
            "jest spyon constructor",
            "jest mock date",
            "jest mock data",
            "jest enzyme context provder context is not used",
            "jest enzyme test context not being updated",
            "jest spyon default import",
            "jest mock exported function",
            "jest mock async function",
            "jest mock async function",
            "jest mocks folder",
            "jest enzyme test componentdidupdate",
            "vscode jest extension",
            "vscode jest",
            "jest \"intersectionobserver\" is not defined",
            "jest IntersectionObserver is not defined",
            "jest ReferenceError: IntersectionObserver is not defined",
            "jest mock not working module",
            "jest mock default export",
            "jest mock an import",
            "jest mock example",
            "jest transformIgnorePatterns",
            "jest test with react.createref",
            "jest mock function",
            "componentDidMount jest shallow not called",
            "async test react jest",
            "jest async test",
            "jest import unexpected token",
            "jest test import scss",
        ],
        entityWords: [
            "jest",
        ],
    },
    {
        containingQueries: [
            "reactadd storybook",
            "storybook",
            "storybook static",
            "eyes applitools storybook Test is finished but no results returned.",
            "eyes applitools storybook Test is finished but no results returned.\\",
            "eyes applitool storybook Test is finished but no results returned.\\",
            "\"JSHandle:getting stories from storybook. isV2= JSHandle:true\"",
            "JSHandle:getting stories from storybook. isV2= JSHandle:true",
            "install storybook",
            "storybook and css variables",
            "storybook/app/react/bin/build.js",
            "npm storybook 1.7.1",
            "github storybook",
            "storybook static production",
            "storybook do not build on error",
            "storybook decorators",
            "node module typescript storybook syntax error",
            "jsdom unexpected token storybook",
            "jsdom unexpected token \"applitools\" storybook",
            "storybook recommended babelrc",
            "storybook babelrc",
            "storybook babelrc",
            "storybook build static es module",
            "run storybook and pass env vars to stories",
            "storybook default config",
            "applitools eyes configure jsdom storybook",
            "\"Failed to launch chrome!\" storybook applitools",
            "Failed to launch chrome! storybook applitools",
            "applitools eyes configure jsdom storybook",
            "applitools storybook eyes",
            "jsdom unexpected token \"applitools\" storybook",
            "jsdom unexpected token applitools storybook",
            "applitools eyes storybook \"unexpected\" symbol",
            "applitools eyes storybook unexpected symbol",
            "storybook preview bundle js",
            "react storybook click",
            "@applitools/eyes.storybook",
            "@applitools/eyes.storybook eyes-storybook Could not open http://localhost:6006/ inside a browser",
            "@applitools/eyes.storybook \"--ci\"",
            "@applitools/eyes.storybook --ci",
            "storybook ERR! Could not open http://localhost:6006/ inside a browser. If you're running this command inside a",
            "docker storybook No git binary found in $PATH",
            "adding storybook",
        ],
        entityWords: [
            "storybook",
        ],
    },
    {
        containingQueries: [
            "css grid force column width",
            "intellij do not suggest css optimization",
            "margin css shorthand",
            "css variables",
            "css flex tutorial",
            "css bounce effect",
            "css do not break line",
            "linear equation for grid css size",
            "css grid",
            "css variable gets reset to 0 inline style html",
            "css variable gets reset to 0",
            "css variables example codepen",
            "css variables example",
            "storybook and css variables",
            "chrome see all css variables",
            "sass css variables",
            "css multiplying by css variable",
            "controlling css variables from js",
            "css variables sexample",
            "css linear gradient",
            "css hide the scrollbar",
            "css offset scrollbar into parent",
            "css customize scrollbar position",
            "css change scrollbar position",
            "css scrollbar in middle of div",
            "css customizing scrollbar",
            "vscode go to react class css",
            "css value formatters",
            "css override inline style",
            "css first of class name anywhere",
            "css first of classname anywhere",
            "css no line break",
            "css filter change color",
            "css modules typescript webpack",
            "css units of measure",
            "css counter",
            "css empty selector",
            "caniuse css attr selectors",
            "caniuse css attribute selectors",
        ],
        entityWords: [
            "css",
        ],
    },
    {
        containingQueries: [
            "typescript inline key index",
            "intellij code analysis \"slow\" typescript",
            "typescript Stateless Functional Components",
            "typescript specify key",
            "jest perform type check typescript",
            "typescript compile dry",
            "intellij typescript type check all",
            "typescript constructor public readonly",
            "typescript constructor publicreadonly",
            "typescript constructor public",
            "typescript declare type globally",
            "typescript declare global",
            "typescript create sorted copy",
            "typescript break array to tuple",
            "typescript conditionally add property to array",
            "typescript conditionally add property to object",
            "optional options in typescript",
            "typescript or operator zero",
            "typescript or operand zero",
            "babel 7 webpack typescript",
            "babel 7 with typescript",
            "node module typescript storybook syntax error",
            "typescript import es module",
            "react typescript ref type",
            "css modules typescript webpack",
            "sass style loader classes typescript",
            "typescript exclude from interface",
            "typescript interface extends minus one field",
            "typescript on of types",
            "react render props type typescript",
            "typescript sleep",
            "typescript define async const",
            "typescript define async",
            "typescript interface function async",
            "react components with typescript generic",
            "\"cannot find name document\" intellij typescript",
            "create react app typescript",
        ],
        entityWords: [
            "typescript",
        ],
    },
    {
        containingQueries: [
            "npm stopwords",
            "npm jest esm",
            "free chart generator npm",
            "spline charts npm \"free\"",
            "spline charts npm free",
            "spline charts npm",
            "npm optional dependencies",
            "npm storybook 1.7.1",
            "npm jsdom \"Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)\"",
            "npm jsdom Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)",
            "npm preinstall",
            "npm create react app",
            "npm show version list",
            "npm explore older versions of package",
            "npm ignore puppeteer in package lock",
            "Chromium revision is not downloaded. Run \"npm install\" or \"yarn install\" docker",
            "Chromium revision is not downloaded. Run \"npm install\" or \"yarn install\"",
            "Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)",
            "npm wait-on",
            "concurrently npm",
            "react classnames npm",
            "fusioncharts npm",
            "rimraf npm",
            "npm prop-types",
            "core-js npm",
            "npm classnames",
            "validator npm",
            "npm icon",
            "npm icon",
            "npm package icon",
            "npm package icon",
            "npm package icon transparent",
        ],
        entityWords: [
            "npm",
        ],
    },
    {
        containingQueries: [
            "can webpack shake global variables",
            "webpack terser production",
            "corrupted webpack production",
            "terser keep_fname 1 char webpack",
            "webpack production mode",
            "webpack corrupts files when in mode production",
            "webpack corrupts files when in mode production",
            "webpack build production unexpected syntax run",
            "\"terserplugin\" library syntax error webpack",
            "TerserPlugin library syntax error webpack",
            "babel 7 webpack typescript",
            "webpack add babel tsloader",
            "webpack add babel",
            "webpack 4 optimization",
            "webpack 4 foncifure compression",
            "webpack node modules bundles in the wrong way",
            "webpack config loader exclude but one",
            "webpack add babel",
            "webpack add babel",
            "webpack loader exclude except",
            "webpack loader exclude include",
            "webpack transpile es modules",
            "webpack es module loader",
            "webpack es loader",
            "css modules typescript webpack",
            "url-loader not found webpack font",
            "url-loader not found webpack",
            "webpack and scss globals",
            "sass compiler webpack global",
            "webpack hot reload",
            "webpack manifest plugin",
        ],
        entityWords: [
            "webpack",
        ],
    },
    {
        containingQueries: [
            "applitools",
            "applitools",
            "eyes applitools storybook Test is finished but no results returned.",
            "eyes applitools storybook Test is finished but no results returned.\\",
            "applitools treat new tests as failed",
            "jsdom unexpected token \"applitools\" storybook",
            "eyes applitools visual grid",
            "eyes applitools visualgrid",
            "building applitools for jsdom",
            "amit zur applitools mail",
            "amitzur applitools mail",
            "applitools eyes github",
            "applitools eyes",
            "applitools eyes docker puppeteer",
            "applitools eyes",
            "applitools eyes configure jsdom storybook",
            "Running as root without --no-sandbox is not supported \"applitools\"",
            "Running as root without --no-sandbox is not supported applitools",
            "\"Failed to launch chrome!\" storybook applitools",
            "Failed to launch chrome! storybook applitools",
            "applitools eyes configure jsdom storybook",
            "applitools eyes configure jsdom",
            "applitools storybook eyes",
            "jsdom unexpected token \"applitools\" storybook",
            "jsdom unexpected token applitools storybook",
            "applitools eyes storybook \"unexpected\" symbol",
            "applitools eyes storybook unexpected symbol",
        ],
        entityWords: [
            "applitools",
        ],
    },
    {
        containingQueries: [
            "visual sudio code run single test",
            "react test id",
            "should i test for react state",
            "intellij \"test.tsx\" files mark as test files",
            "intellij \"test.tsx\" files",
            "intellij mark test files by extension",
            "intellij mark test files regex",
            "intellij mark test files",
            "eyes applitools storybook Test is finished but no results returned.",
            "eyes applitools storybook Test is finished but no results returned.\\",
            "eyes applitool storybook Test is finished but no results returned.\\",
            "eyes applitool Test is finished but no results returned.\\",
            "jest enzyme test context not being updated",
            "jest enzyme test componentdidupdate",
            "ewebpack loader ignore test files",
            "react dom intersectionobserver \"test\"",
            "react enzyme test child props",
            "intellij automatically mark test files",
            "jest test with react.createref",
            "react test with context",
            "async test react jest",
            "jest async test",
            "fake wsrequest play scala test",
            "jest test import scss",
            "SecurityError: localStorage is not available for opaque origins test",
        ],
        entityWords: [
            "test",
        ],
    },
    {
        containingQueries: [
            "scala java.util.Map to json",
            "scala must equal with comparator",
            "play scala mockito get arguments of last call",
            "play scala mockito geet arguments of last call",
            "scala building jsValue",
            "fake wsresponse play scala",
            "scala mockito match any class",
            "fake wsrequest play scala test",
            "scala mockito any matcher",
            "scala mockito mock",
            "smockito example scala",
            "play scala fake \"wsclient\" for tests",
            "play scala fake wsclient for tests",
            "scala building a map",
            "scala.runtime.NonLocalReturnControl: null",
            "play api make request scala",
            "scala sequence to parameter star",
            "scala sequence to asterik",
            "scala asterisk",
            "play 2.6 scala actionbuilder get cookies",
            "play scala get cookies from request",
            "play scala expression of type result action[anycontent]",
            "play scala expression of type result",
            "scala play returning future ok",
        ],
        entityWords: [
            "scala",
        ],
    },
    {
        containingQueries: [
            "enzyme click element",
            "enzyme await for find",
            "enzyme multiple results from selector",
            "enzyme filter by key",
            "jest enzyme check for attribute",
            "wrap jsx element enzyme",
            "enzyme get text of eleemtn",
            "enzyme find by react key",
            "enzyme dive",
            "enzyme shallow steps",
            "jest enzyme context provder context is not used",
            "jest enzyme test context not being updated",
            "jest enzyme test componentdidupdate",
            "react enzyme test child props",
            "enzyme get react ref",
            "enzyme get id of element",
            "enzyme get child prop",
            "enzyme get first child",
            "enzyme wait for props propagate to childs",
            "enzyme check props passed to child",
            "enzyme mount",
            "enzyme check state of child component",
            "enzyme not exist",
            "react enzyme testshallow render",
        ],
        entityWords: [
            "enzyme",
        ],
    },
    {
        containingQueries: [
            "intellij code analysis \"slow\" typescript",
            "visual sudio code run single test",
            "jest visual studio code window",
            "visual studio code snippets",
            "visual studio code run tests jest",
            "visual studio code run tests",
            "visual studio code go next line on comment",
            "intellij code analysis \"slow\" typesciript",
            "intellij code analysis \"slow\"",
            "intellij code analysis \"slow\"",
            "intellij code analysis \"slow\"",
            "intellij code analysis slow",
            "intellij code analysis slow",
            "intellij code analysis slow",
            "vs code go to scss file",
            "visual code from intellij",
            "visual code",
            "Eyes: log():Error on getting stories: Error: Request failed with status code",
            "\"Eyes: log():Error on getting stories: Error: Request failed with status code\"",
            "\"Eyes: log():Error on getting stories: Error: Request failed with status code 404\"",
            "Eyes: log():Error on getting stories: Error: Request failed with status code 404",
            "google slides font for code",
            "complex code",
            "complex code",
        ],
        entityWords: [
            "code",
        ],
    },
    {
        containingQueries: [
            "js max min",
            "js date formatMatcher",
            "date formant js",
            "js x days ago",
            "js day diff from dates",
            "js array repeat",
            "js get difference between date strings",
            "js capitalize",
            "jest transform js files",
            "js locale day of week by date",
            "controlling css variables from js",
            "storybook/app/react/bin/build.js",
            "js format date",
            "js get today",
            "js format number",
            "format as percentage js",
            "\"Cannot assign empty object or null\" js",
            "how to know which module system an existing js",
            "storybook preview bundle js",
            "react js roadmap",
            "tabs communication library js",
            "async promise example js",
        ],
        entityWords: [
            "js",
        ],
    },
    {
        containingQueries: [
            "jsdom polyfilling \"canvas\" \"getcontext\"",
            "jsdom polyfilling canvas getcontext",
            "npm jsdom \"Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)\"",
            "npm jsdom Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)",
            "Error: Not implemented: HTMLCanvasElement.prototype.getContext jsdom",
            "jsdom unexpected token storybook",
            "jsdom unexpected token",
            "jsdom unexpected token \"applitools\" storybook",
            "jsdom unexpected token",
            "jsdom es modules",
            "jsdom requestanimationframe -jest",
            "jsdom requestanimationframe",
            "fusioncharts \"jsdom\"",
            "fusioncharts jsdom",
            "jusioncharts jsdom",
            "jsdom es modules",
            "building applitools for jsdom",
            "applitools eyes configure jsdom storybook",
            "applitools eyes configure jsdom storybook",
            "applitools eyes configure jsdom",
            "jsdom unexpected token \"applitools\" storybook",
            "jsdom unexpected token applitools storybook",
        ],
        entityWords: [
            "jsdom",
        ],
    },
    {
        containingQueries: [
            "loading png transparent background",
            "loading png transparent background",
            "loading png transparent background",
            "loading png transparent",
            "loading png transparent",
            "loading png transparent",
            "loading png transparent",
            "mail transparent background",
            "mail unread transparent background",
            "mail unread transparent background",
            "mail unread transparent background",
            "transparent backgroundbucket",
            "transparent backgroundbucket",
            "transparent backgroundbucket",
            "google transparent logo",
            "google transparent logo",
            "npm package icon transparent",
            "open package icon transparent",
            "open package icon transparent",
            "package icon transparent",
            "package icon transparent",
        ],
        entityWords: [
            "transparent",
        ],
    },
    {
        containingQueries: [
            "intellij code analysis \"slow\" typescript",
            "intellij code analysis \"slow\" typesciript",
            "intellij code analysis \"slow\"",
            "intellij code analysis \"slow\"",
            "intellij code analysis \"slow\"",
            "intellij code analysis slow",
            "intellij code analysis slow",
            "intellij code analysis slow",
            "intellij typescript type check all",
            "intellij do not suggest css optimization",
            "intellij \"test.tsx\" files mark as test files",
            "intellij \"test.tsx\" files",
            "intellij mark test files by extension",
            "intellij mark test files regex",
            "intellij mark test files",
            "intellij prevent scss grid-template-areas auto format",
            "visual code from intellij",
            "intellij automatically mark test files",
            "\"cannot find name document\" intellij typescript",
            "cannot find name document intellij",
        ],
        entityWords: [
            "intellij",
        ],
    },
    {
        containingQueries: [
            "jest \"SyntaxError: Unexpected token export\" es modules",
            "jest SyntaxError: Unexpected token export",
            "webpack build production unexpected syntax run",
            "\"fusioncharts\" unexpected token",
            "fusioncharts unexpected token",
            "jsdom unexpected token storybook",
            "jsdom unexpected token",
            "jsdom unexpected token \"applitools\" storybook",
            "SyntaxError: Unexpected token ( babel",
            "jsdom unexpected token",
            "exmascript modules mismatch unexpected symbol",
            "\"fusioncharts\" \"unexpected token (\"",
            "fusioncharts \"unexpected token (\"",
            "fusioncharts \"unexpected token\"",
            "fusioncharts unexpected token",
            "jsdom unexpected token \"applitools\" storybook",
            "jsdom unexpected token applitools storybook",
            "applitools eyes storybook \"unexpected\" symbol",
            "applitools eyes storybook unexpected symbol",
            "jest import unexpected token",
        ],
        entityWords: [
            "unexpected",
        ],
    },
    {
        containingQueries: [
            "fusioncharts crispedges",
            "fusioncharts installing a license",
            "fusioncharts turn off animation",
            "fusioncharts scroll to end",
            "fusioncharts scroll causes flicker",
            "fusioncharts events",
            "\"fusioncharts\" unexpected token",
            "fusioncharts unexpected token",
            "\"fusioncharts\" \"unexpected token (\"",
            "fusioncharts \"unexpected token (\"",
            "fusioncharts \"unexpected token\"",
            "fusioncharts unexpected token",
            "fusioncharts \"jsdom\"",
            "fusioncharts jsdom",
            "fusioncharts tchart tooltext",
            "fusioncharts tooltip",
            "fusioncharts",
            "fusioncharts license",
            "fusioncharts npm",
            "fusioncharts data visualization",
        ],
        entityWords: [
            "fusioncharts",
        ],
    },
    {
        containingQueries: [
            "eyes applitools storybook Test is finished but no results returned.",
            "eyes applitools storybook Test is finished but no results returned.\\",
            "eyes applitool storybook Test is finished but no results returned.\\",
            "eyes applitool Test is finished but no results returned.\\",
            "eyes applitools visual grid",
            "eyes applitools visualgrid",
            "applitools eyes github",
            "applitools eyes",
            "applitools eyes docker puppeteer",
            "applitools eyes",
            "applitools eyes configure jsdom storybook",
            "applitools eyes configure jsdom storybook",
            "applitools eyes configure jsdom",
            "applitools storybook eyes",
            "applitools eyes storybook \"unexpected\" symbol",
            "applitools eyes storybook unexpected symbol",
            "@applitools/eyes.storybook",
            "@applitools/eyes.storybook eyes-storybook Could not open http://localhost:6006/ inside a browser",
            "@applitools/eyes.storybook \"--ci\"",
            "@applitools/eyes.storybook --ci",
        ],
        entityWords: [
            "eyes",
        ],
    },
    {
        containingQueries: [
            "play scala mockito get arguments of last call",
            "play scala mockito geet arguments of last call",
            "fake wsresponse play scala",
            "fake wsrequest play scala test",
            "play scala fake \"wsclient\" for tests",
            "play scala fake wsclient for tests",
            "play argumet param port",
            "play cookies to wscookies",
            "play api make request scala",
            "play api make request",
            "play cookies to wscooies",
            "play cookies to wscookide",
            "play 2.6 scala actionbuilder get cookies",
            "play scala get cookies from request",
            "play scala expression of type result action[anycontent]",
            "play scala expression of type result",
            "scala play returning future ok",
            "play config not found in path",
            "play conf file 2.6",
            "play react seed",
        ],
        entityWords: [
            "play",
        ],
    },
    {
        containingQueries: [
            "javascript string replace all",
            "javascript format date yyyy-mm-dd",
            "javascript date start of day",
            "javascript find first",
            "javascript date today without time",
            "javascript date today",
            "javascript conver day to ms",
            "javascript syntax checker",
            "javascript first n",
            "new date() vs date.now() javascript",
            "addeventhandler javascript scroll",
            "javascript iterate \"dates\" start end",
            "javascript iterate dates",
            "javascript get yesterday date",
            "javascript random",
            "history html javascript",
            "history javascript browser iframe",
            "history javascript browser iframe",
            "history javascript browser",
        ],
        entityWords: [
            "javascript",
        ],
    },
    {
        containingQueries: [
            "background image as inline svg",
            "image online remove background",
            "10 commandments background",
            "10 commandments background",
            "stone background",
            "stone background",
            "stone background",
            "stone background",
            "stone background",
            "stone background",
            "stone background",
            "stone background",
            "loading png transparent background",
            "loading png transparent background",
            "loading png transparent background",
            "mail transparent background",
            "mail unread transparent background",
            "mail unread transparent background",
            "mail unread transparent background",
        ],
        entityWords: [
            "background",
        ],
    },
    {
        containingQueries: [
            "breadcrumbs material design",
            "breadcrumbs material design",
            "breadcrumbs material design",
            "breadcrumbs ui",
            "breadcrumbs ui",
            "breadcrumbs ui",
            "breadcrumbs ui",
            "breadcrumbs ui",
            "breadcrumbs ui",
            "breadcrumbs ui",
            "breadcrumbs ui",
            "breadcrumbs trail",
            "breadcrumbs trail",
            "breadcrumbs trail",
            "breadcrumbs trail",
            "breadcrumbs trail",
            "breadcrumbs trail",
            "breadcrumbs trail",
            "breadcrumbs",
        ],
        entityWords: [
            "breadcrumbs",
        ],
    },
    {
        containingQueries: [
            "background image as inline svg",
            "docker puppeteer \"headless\" docker image",
            "docker puppeteer headlessdocker image",
            "google search image",
            "google search image",
            "image online remove background",
            "image",
            "image",
            "image",
            "image",
            "image",
            "image",
            "image",
            "image",
            "image",
            "google image search",
            "google image search",
            "google docs mask image",
        ],
        entityWords: [
            "image",
        ],
    },
    {
        containingQueries: [
            "postmessage example",
            "highstock example",
            "css variables example codepen",
            "css variables example",
            "babelrc example",
            "react classnames example",
            "jest mock example",
            "media query example",
            "intersection observer example",
            "react context example tsx",
            "react loadable example",
            "smockito example scala",
            "iframe example",
            "micro frontends by example",
            "async promise example js",
            "history html5 example",
            "history html5 example",
        ],
        entityWords: [
            "example",
        ],
    },
    {
        containingQueries: [
            "box shadow inner over content",
            "border box inner over content",
            "whats in the box se7en",
            "whats in the box se7en",
            "whats in the box se7en",
            "whats in the box se7en",
            "whats in the box se7en",
            "whats in the box",
            "whats in the box",
            "google slides box rounded corners",
            "message box pending",
            "message box unread",
            "box in a box",
            "box in a box",
            "put in a box",
            "put in a box",
        ],
        entityWords: [
            "box",
        ],
    },
    {
        containingQueries: [
            "jest \"SyntaxError: Unexpected token export\" es modules",
            "jest SyntaxError: Unexpected token export",
            "\"fusioncharts\" unexpected token",
            "fusioncharts unexpected token",
            "jsdom unexpected token storybook",
            "jsdom unexpected token",
            "jsdom unexpected token \"applitools\" storybook",
            "SyntaxError: Unexpected token ( babel",
            "jsdom unexpected token",
            "\"fusioncharts\" \"unexpected token (\"",
            "fusioncharts \"unexpected token (\"",
            "fusioncharts \"unexpected token\"",
            "fusioncharts unexpected token",
            "jsdom unexpected token \"applitools\" storybook",
            "jsdom unexpected token applitools storybook",
            "jest import unexpected token",
        ],
        entityWords: [
            "token",
        ],
    },
    {
        containingQueries: [
            "stypescript spread argument function object",
            "stypescript spread argument function",
            "react function component",
            "scss function",
            "react setting a global function",
            "jest mock exported function",
            "jest mock async function",
            "jest mock async function",
            "keep_fnames terser \"syntax error\" function name",
            "f(\"function\"!=typeof t&&null!==t)throw new TypeError(\"Super expression must either be null or a funct",
            "super expression must either be null or a function, not object es6",
            "n\"!=typeof t&&null!==t)throw new TypeError(\"Super expression must either be null or a function, not \"+typeof t);",
            "jest mock function",
            "react context function re-render",
            "react context function re-renderer",
            "typescript interface function async",
        ],
        entityWords: [
            "function",
        ],
    },
    {
        containingQueries: [
            "not good enough funny",
            "breathtaking funny meme",
            "breathtaking funny",
            "breathtaking funny",
            "challenge funny",
            "funny yin yang",
            "funny yin yang",
            "funny yin yang",
            "funny yin yang",
            "funny yin yang",
            "balance funny",
            "balance funny",
            "brilliant idea funny",
            "product manager funny",
            "product manager funny",
            "product manager funny",
        ],
        entityWords: [
            "funny",
        ],
    },
    {
        containingQueries: [
            "Error: Evaluation failed: TypeError: Cannot read property '\"children\"' of null",
            "Error: Evaluation failed: TypeError: Cannot read property 'children' of null",
            "vscode cannot \"write\" prettify",
            "vscode cannot write prettify",
            "vscode cannot write pretty",
            "\"Cannot assign empty object or null\" js",
            "\"Cannot assign empty object or null\"",
            "\"TypeError: Cannot assign empty object or null\"",
            "\"TypeError: Cannot assign empty object or null.\"",
            "TypeError: Cannot assign empty object or null.",
            "error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            ".local-chromium/linux-609904/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            "error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            "\"cannot find name document\" intellij typescript",
            "cannot find name document intellij",
            "cannot find name document",
        ],
        entityWords: [
            "cannot",
        ],
    },
    {
        containingQueries: [
            "Running as root without --no-sandbox is not supported \"applitools\"",
            "Running as root without --no-sandbox is not supported applitools",
            "Running as root without --no-sandbox is not supported",
            "ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported",
            "storybook ERR! Could not open http://localhost:6006/ inside a browser. If you're running this command inside a",
            "ERR! Could not open http://localhost:6006/ inside a browser. If you're running this command inside a",
            "kid running away hall gif",
            "kid running away hall gif",
            "kid running away hall gif",
            "kid running away hall gif",
            "kid running away hall gif",
            "kid running away hall gif",
            "kid running away hall gif",
            "kid running away hall gif",
            "kid running away hall gif",
            "kid running away hall gif",
        ],
        entityWords: [
            "running",
        ],
    },
    {
        containingQueries: [
            "sandbox iframe",
            "friendly iframe locally",
            "ie get iframe document",
            "global functions or postmessages iframe",
            "global functions vs postmessages iframe",
            "communicating friendly iframe",
            "friendly iframe get parent window",
            "iframe example",
            "what is an iframe",
            "iframe history object parent",
            "friendly iframe",
            "history javascript browser iframe",
            "history javascript browser iframe",
            "managing history and routes iframe parent child",
            "iframe",
        ],
        entityWords: [
            "iframe",
        ],
    },
    {
        containingQueries: [
            "eyes applitools storybook Test is finished but no results returned.",
            "eyes applitools storybook Test is finished but no results returned.\\",
            "eyes applitool storybook Test is finished but no results returned.\\",
            "eyes applitool Test is finished but no results returned.\\",
            "puppeteer no sandbox",
            "No usable sandbox! Update your kernel docker",
            "error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            ".local-chromium/linux-609904/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            "error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            "css no line break",
            "selenium/standalone-chrome:3.8.1 no git docker",
            "selenium/standalone-chrome:3.8.1 no git",
            "docker storybook No git binary found in $PATH",
            "tslint no implicit any",
            "Namespace 'React' has no exported member 'SVGProps'.",
        ],
        entityWords: [
            "no",
        ],
    },
    {
        containingQueries: [
            "manifest file for a web app",
            "react-dom.development.js:506 Warning: Expected instance state to match memoized state before processing the update queue. This is likely due to a bug in React. Please file an issue.",
            "vs code go to scss file",
            "vs codego to scss file",
            "pupppeteer config file",
            "puppeteer static file config",
            "error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            ".local-chromium/linux-609904/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            "error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            "File node_modules/@types/classNames/index.d.ts is not a module. \"classNames\"",
            "File node_modules/@types/classNames/index.d.ts is not a module.",
            "java.io.FileNotFoundException: \"checkstyle\"-config.xml (No such file or directory)",
            "java.io.FileNotFoundException: checkstyle-config.xml (No such file or directory)",
            "play conf file 2.6",
            "cors file protocol",
        ],
        entityWords: [
            "file",
        ],
    },
    {
        containingQueries: [
            "not good enough meme",
            "chef gordon not good enough meme",
            "chef gordon not good enough meme",
            "chef gordon not good enough meme",
            "not good enough meme",
            "not good enough meme",
            "not good enough meme",
            "breathtaking funny meme",
            "meme gfont",
            "office space meme",
            "office space meme",
            "office space meme",
            "office space meme",
            "office space meme",
        ],
        entityWords: [
            "meme",
        ],
    },
    {
        containingQueries: [
            "missing class properties transform. react babelrc",
            "babel react babelrc",
            "do babelrc transpile \"node_modules\"",
            "do babelrc affect \"node_modules\"",
            "do babelrc affect node_modules",
            "do babelrc affect node modules",
            "babelrc transform-es2015-modules-commonjs",
            "recommended babelrc",
            "storybook recommended babelrc",
            "babelrc extend default",
            "babelrc es modules",
            "babelrc example",
            "storybook babelrc",
            "storybook babelrc",
        ],
        entityWords: [
            "babelrc",
        ],
    },
    {
        containingQueries: [
            "google search image",
            "google search image",
            "google slides font for code",
            "google image search",
            "google image search",
            "google slides add template slide",
            "google slides box rounded corners",
            "google transparent logo",
            "google transparent logo",
            "google",
            "google",
            "google slides save animation",
            "google slides save animation",
            "google docs mask image",
        ],
        entityWords: [
            "google",
        ],
    },
    {
        containingQueries: [
            "javascript format date yyyy-mm-dd",
            "js date formatMatcher",
            "date formant js",
            "javascript date start of day",
            "js get difference between date strings",
            "javascript date today without time",
            "javascript date today",
            "date to utc",
            "js locale day of week by date",
            "js format date",
            "new date() vs date.now() javascript",
            "jest mock date",
            "javascript get yesterday date",
        ],
        entityWords: [
            "date",
        ],
    },
    {
        containingQueries: [
            "jest transform js files",
            "see webpackdevserver files",
            "intellij \"test.tsx\" files mark as test files",
            "intellij \"test.tsx\" files",
            "intellij mark test files by extension",
            "intellij mark test files regex",
            "intellij mark test files",
            "webpack corrupts files when in mode production",
            "webpack corrupts files when in mode production",
            "ewebpack loader ignore test files",
            "intellij automatically mark test files",
            "crucible ignore certain files",
            "error: The following untracked working tree files would be overwritten by checkout:",
        ],
        entityWords: [
            "files",
        ],
    },
    {
        containingQueries: [
            "Error: Evaluation failed: TypeError: Cannot read property '\"children\"' of null",
            "Error: Evaluation failed: TypeError: Cannot read property 'children' of null",
            "npm jsdom \"Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)\"",
            "npm jsdom Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)",
            "Error: Not implemented: HTMLCanvasElement.prototype.getContext jsdom",
            "Error: Failed to replace env in config:",
            "Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)",
            "Module not found: Error: Can't resolve './fonts/ProximaNova-Light.woff'",
            "Eyes: log():Error on getting stories: Error: Request failed with status code",
            "\"Eyes: log():Error on getting stories: Error: Request failed with status code\"",
            "\"Eyes: log():Error on getting stories: Error: Request failed with status code 404\"",
            "Eyes: log():Error on getting stories: Error: Request failed with status code 404",
            "error: The following untracked working tree files would be overwritten by checkout:",
        ],
        entityWords: [
            "error:",
        ],
    },
    {
        containingQueries: [
            "ewebpack loader ignore test files",
            "babel loader using wrong babel version 7",
            "babel loader Couldn't find preset \"@babel/react\" relative to directory",
            "should i use ts loader or babel",
            "webpack config loader exclude but one",
            "webpack loader exclude except",
            "webpack loader exclude include",
            "webpack es module loader",
            "webpack es loader",
            "postcss loader",
            "sass style loader classes typescript",
            "sass style loader",
            "sass url loader",
        ],
        entityWords: [
            "loader",
        ],
    },
    {
        containingQueries: [
            "babel preset react app",
            "babel loader using wrong babel version 7",
            "babel react babelrc",
            "babel loader Couldn't find preset \"@babel/react\" relative to directory",
            "babel 7 webpack typescript",
            "babel 7 with typescript",
            "should i use ts loader or babel",
            "webpack add babel tsloader",
            "webpack add babel",
            "SyntaxError: Unexpected token ( babel",
            "babel extend default",
            "webpack add babel",
            "webpack add babel",
        ],
        entityWords: [
            "babel",
        ],
    },
    {
        containingQueries: [
            "package json _inBundle",
            "? write(JSON.parse(require('fs').readFileSync('./package.json')).version);",
            "npm explore older versions of package",
            "npm ignore puppeteer in package lock",
            "package in package",
            "package in package",
            "npm package icon",
            "npm package icon",
            "npm package icon transparent",
            "open package icon transparent",
            "open package icon transparent",
            "package icon transparent",
            "package icon transparent",
        ],
        entityWords: [
            "package",
        ],
    },
    {
        containingQueries: [
            "error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            ".local-chromium/linux-609904/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            "error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            "loading png transparent background",
            "loading png transparent background",
            "loading png transparent background",
            "loading png transparent",
            "loading png transparent",
            "loading png transparent",
            "loading png transparent",
            "loading png",
            "loading png",
            "loading png",
        ],
        entityWords: [
            "loading",
        ],
    },
    {
        containingQueries: [
            "message icon",
            "message icon",
            "message icon",
            "message icon",
            "npm icon",
            "npm icon",
            "npm package icon",
            "npm package icon",
            "npm package icon transparent",
            "open package icon transparent",
            "open package icon transparent",
            "package icon transparent",
            "package icon transparent",
        ],
        entityWords: [
            "icon",
        ],
    },
    {
        containingQueries: [
            "global functions vs postmessages iframe",
            "import vs require multiple",
            "import vs require",
            "rquire vs import lazy",
            "rquire vs import",
            "new date() vs date.now() javascript",
            "vs code go to scss file",
            "vs codego to scss file",
            "commonjs vs es6",
            "autosave vs manual button",
            "autosave vs save button",
            "autosave vs save button",
        ],
        entityWords: [
            "vs",
        ],
    },
    {
        containingQueries: [
            "visual sudio code run single test",
            "visual studio code run tests jest",
            "visual studio code run tests",
            "visual studio run tests",
            "componentWillReceiveProps run only on partial change",
            "webpack build production unexpected syntax run",
            "run storybook and pass env vars to stories",
            "docker run entrypoint as non-root",
            "docker run as non-root",
            "Chromium revision is not downloaded. Run \"npm install\" or \"yarn install\" docker",
            "Chromium revision is not downloaded. Run \"npm install\" or \"yarn install\"",
            "puppeteer run headless",
        ],
        entityWords: [
            "run",
        ],
    },
    {
        containingQueries: [
            "stypescript spread argument function object",
            "typescript conditionally add property to object",
            "\"Cannot assign empty object or null\" js",
            "\"Cannot assign empty object or null\"",
            "\"TypeError: Cannot assign empty object or null\"",
            "\"TypeError: Cannot assign empty object or null.\"",
            "TypeError: Cannot assign empty object or null.",
            "super expression must either be null or a function, not object es6",
            "error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            ".local-chromium/linux-609904/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            "error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory",
            "iframe history object parent",
        ],
        entityWords: [
            "object",
        ],
    },
    {
        containingQueries: [
            "import vs require multiple",
            "import vs require",
            "rquire vs import lazy",
            "rquire vs import",
            "jest spyon default import",
            "conditional import",
            "typescript import es module",
            "es6 import es5 module",
            "jest mock an import",
            "node sass import once",
            "jest import unexpected token",
            "jest test import scss",
        ],
        entityWords: [
            "import",
        ],
    },
];

export default {
    entitiesDataSet1,
};
